# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'morfeus_pyqt.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_moRFeus_Qt(object):
    def setupUi(self, moRFeus_Qt):
        moRFeus_Qt.setObjectName(_fromUtf8("moRFeus_Qt"))
        moRFeus_Qt.resize(369, 287)
        moRFeus_Qt.setMinimumSize(QtCore.QSize(369, 269))
        moRFeus_Qt.setMaximumSize(QtCore.QSize(369, 287))
        self.moRFeus = QtGui.QWidget(moRFeus_Qt)
        self.moRFeus.setEnabled(True)
        self.moRFeus.setMinimumSize(QtCore.QSize(369, 250))
        self.moRFeus.setMaximumSize(QtCore.QSize(369, 250))
        self.moRFeus.setObjectName(_fromUtf8("moRFeus"))
        self.startLabel = QtGui.QLabel(self.moRFeus)
        self.startLabel.setGeometry(QtCore.QRect(10, 12, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.startLabel.setFont(font)
        self.startLabel.setObjectName(_fromUtf8("startLabel"))
        self.label_3 = QtGui.QLabel(self.moRFeus)
        self.label_3.setGeometry(QtCore.QRect(10, 42, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.moRFeus)
        self.label_4.setGeometry(QtCore.QRect(10, 72, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.moRFeus)
        self.label_5.setGeometry(QtCore.QRect(10, 102, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.stepSize = QtGui.QDoubleSpinBox(self.moRFeus)
        self.stepSize.setGeometry(QtCore.QRect(110, 70, 161, 22))
        self.stepSize.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.stepSize.setDecimals(4)
        self.stepSize.setMinimum(0.001)
        self.stepSize.setMaximum(50000.0)
        self.stepSize.setProperty("value", 250.0)
        self.stepSize.setObjectName(_fromUtf8("stepSize"))
        self.endFreq = QtGui.QDoubleSpinBox(self.moRFeus)
        self.endFreq.setGeometry(QtCore.QRect(110, 40, 161, 22))
        self.endFreq.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.endFreq.setDecimals(6)
        self.endFreq.setMinimum(85.0)
        self.endFreq.setMaximum(5400.0)
        self.endFreq.setProperty("value", 88.0)
        self.endFreq.setObjectName(_fromUtf8("endFreq"))
        self.startFreq = QtGui.QDoubleSpinBox(self.moRFeus)
        self.startFreq.setGeometry(QtCore.QRect(110, 10, 161, 22))
        font = QtGui.QFont()
        font.setKerning(True)
        self.startFreq.setFont(font)
        self.startFreq.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.startFreq.setDecimals(6)
        self.startFreq.setMinimum(85.0)
        self.startFreq.setMaximum(5400.0)
        self.startFreq.setSingleStep(0.1)
        self.startFreq.setProperty("value", 85.0)
        self.startFreq.setObjectName(_fromUtf8("startFreq"))
        self.powerInput = QtGui.QSpinBox(self.moRFeus)
        self.powerInput.setGeometry(QtCore.QRect(110, 100, 161, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.powerInput.setFont(font)
        self.powerInput.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.powerInput.setMaximum(7)
        self.powerInput.setProperty("value", 1)
        self.powerInput.setObjectName(_fromUtf8("powerInput"))
        self.steps = QtGui.QSpinBox(self.moRFeus)
        self.steps.setGeometry(QtCore.QRect(110, 130, 161, 22))
        self.steps.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.steps.setMaximum(1000)
        self.steps.setProperty("value", 5)
        self.steps.setObjectName(_fromUtf8("steps"))
        self.label_6 = QtGui.QLabel(self.moRFeus)
        self.label_6.setGeometry(QtCore.QRect(10, 132, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.moRFeus)
        self.label_7.setGeometry(QtCore.QRect(10, 162, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.delay = QtGui.QSpinBox(self.moRFeus)
        self.delay.setGeometry(QtCore.QRect(110, 160, 161, 22))
        self.delay.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.delay.setMaximum(10000)
        self.delay.setProperty("value", 1)
        self.delay.setObjectName(_fromUtf8("delay"))
        self.noiseButton = QtGui.QPushButton(self.moRFeus)
        self.noiseButton.setGeometry(QtCore.QRect(285, 70, 75, 23))
        self.noiseButton.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.noiseButton.setFont(font)
        self.noiseButton.setObjectName(_fromUtf8("noiseButton"))
        self.label = QtGui.QLabel(self.moRFeus)
        self.label.setGeometry(QtCore.QRect(10, 192, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.morseButton = QtGui.QPushButton(self.moRFeus)
        self.morseButton.setGeometry(QtCore.QRect(285, 190, 75, 23))
        self.morseButton.setObjectName(_fromUtf8("morseButton"))
        self.biasOn = QtGui.QPushButton(self.moRFeus)
        self.biasOn.setGeometry(QtCore.QRect(285, 130, 75, 23))
        self.biasOn.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.biasOn.setFont(font)
        self.biasOn.setObjectName(_fromUtf8("biasOn"))
        self.genButton = QtGui.QPushButton(self.moRFeus)
        self.genButton.setGeometry(QtCore.QRect(285, 40, 75, 23))
        self.genButton.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.genButton.setFont(font)
        self.genButton.setObjectName(_fromUtf8("genButton"))
        self.biasOff = QtGui.QPushButton(self.moRFeus)
        self.biasOff.setGeometry(QtCore.QRect(285, 160, 75, 23))
        self.biasOff.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.biasOff.setFont(font)
        self.biasOff.setObjectName(_fromUtf8("biasOff"))
        self.sweepButton = QtGui.QPushButton(self.moRFeus)
        self.sweepButton.setGeometry(QtCore.QRect(285, 100, 75, 23))
        self.sweepButton.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sweepButton.setFont(font)
        self.sweepButton.setObjectName(_fromUtf8("sweepButton"))
        self.mixButton = QtGui.QPushButton(self.moRFeus)
        self.mixButton.setGeometry(QtCore.QRect(285, 10, 75, 23))
        self.mixButton.setMaximumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mixButton.setFont(font)
        self.mixButton.setObjectName(_fromUtf8("mixButton"))
        self.morseInput = QtGui.QLineEdit(self.moRFeus)
        self.morseInput.setGeometry(QtCore.QRect(110, 190, 161, 22))
        self.morseInput.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.SouthAfrica))
        self.morseInput.setObjectName(_fromUtf8("morseInput"))
        self.readReg = QtGui.QLineEdit(self.moRFeus)
        self.readReg.setGeometry(QtCore.QRect(110, 220, 161, 22))
        self.readReg.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.readReg.setReadOnly(True)
        self.readReg.setObjectName(_fromUtf8("readReg"))
        self.readRegButton = QtGui.QPushButton(self.moRFeus)
        self.readRegButton.setGeometry(QtCore.QRect(285, 220, 75, 23))
        self.readRegButton.setObjectName(_fromUtf8("readRegButton"))
        self.label_2 = QtGui.QLabel(self.moRFeus)
        self.label_2.setGeometry(QtCore.QRect(10, 222, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        moRFeus_Qt.setCentralWidget(self.moRFeus)
        self.statusbar = QtGui.QStatusBar(moRFeus_Qt)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        moRFeus_Qt.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(moRFeus_Qt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 369, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.menubar.setFont(font)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMoRFeus = QtGui.QMenu(self.menubar)
        self.menuMoRFeus.setObjectName(_fromUtf8("menuMoRFeus"))
        moRFeus_Qt.setMenuBar(self.menubar)
        self.actionVersion_0_369 = QtGui.QAction(moRFeus_Qt)
        self.actionVersion_0_369.setObjectName(_fromUtf8("actionVersion_0_369"))
        self.actionOpen_SDRplot = QtGui.QAction(moRFeus_Qt)
        self.actionOpen_SDRplot.setObjectName(_fromUtf8("actionOpen_SDRplot"))
        self.actionVersion_0_969 = QtGui.QAction(moRFeus_Qt)
        self.actionVersion_0_969.setObjectName(_fromUtf8("actionVersion_0_969"))
        self.actionMessenger = QtGui.QAction(moRFeus_Qt)
        self.actionMessenger.setObjectName(_fromUtf8("actionMessenger"))
        self.menuMoRFeus.addAction(self.actionVersion_0_969)
        self.menubar.addAction(self.menuMoRFeus.menuAction())
        self.startLabel.setBuddy(self.startFreq)
        self.label_3.setBuddy(self.endFreq)
        self.label_4.setBuddy(self.stepSize)
        self.label_5.setBuddy(self.powerInput)
        self.label_6.setBuddy(self.steps)
        self.label_7.setBuddy(self.delay)

        self.retranslateUi(moRFeus_Qt)
        QtCore.QMetaObject.connectSlotsByName(moRFeus_Qt)
        moRFeus_Qt.setTabOrder(self.startFreq, self.endFreq)
        moRFeus_Qt.setTabOrder(self.endFreq, self.stepSize)
        moRFeus_Qt.setTabOrder(self.stepSize, self.powerInput)
        moRFeus_Qt.setTabOrder(self.powerInput, self.steps)
        moRFeus_Qt.setTabOrder(self.steps, self.delay)
        moRFeus_Qt.setTabOrder(self.delay, self.mixButton)
        moRFeus_Qt.setTabOrder(self.mixButton, self.genButton)
        moRFeus_Qt.setTabOrder(self.genButton, self.noiseButton)
        moRFeus_Qt.setTabOrder(self.noiseButton, self.sweepButton)
        moRFeus_Qt.setTabOrder(self.sweepButton, self.biasOn)
        moRFeus_Qt.setTabOrder(self.biasOn, self.biasOff)
        moRFeus_Qt.setTabOrder(self.biasOff, self.morseButton)

    def retranslateUi(self, moRFeus_Qt):
        moRFeus_Qt.setWindowTitle(_translate("moRFeus_Qt", "moRFeus_Qt", None))
        self.startLabel.setText(_translate("moRFeus_Qt", "Device Frequency", None))
        self.label_3.setText(_translate("moRFeus_Qt", "Step Size + Steps", None))
        self.label_4.setText(_translate("moRFeus_Qt", "Step KHz", None))
        self.label_5.setText(_translate("moRFeus_Qt", "Power", None))
        self.label_6.setText(_translate("moRFeus_Qt", "Steps", None))
        self.label_7.setText(_translate("moRFeus_Qt", "Signal delay ms", None))
        self.noiseButton.setText(_translate("moRFeus_Qt", "Noise", None))
        self.label.setText(_translate("moRFeus_Qt", "Morse Code", None))
        self.morseButton.setText(_translate("moRFeus_Qt", "Send Msg", None))
        self.biasOn.setText(_translate("moRFeus_Qt", "Bias On", None))
        self.genButton.setText(_translate("moRFeus_Qt", "Gen", None))
        self.biasOff.setText(_translate("moRFeus_Qt", "Bias Off", None))
        self.sweepButton.setText(_translate("moRFeus_Qt", "Sweep", None))
        self.mixButton.setText(_translate("moRFeus_Qt", "Mixer", None))
        self.readRegButton.setText(_translate("moRFeus_Qt", "Read Reg", None))
        self.label_2.setText(_translate("moRFeus_Qt", "Register", None))
        self.menuMoRFeus.setTitle(_translate("moRFeus_Qt", "MoRFeus", None))
        self.actionVersion_0_369.setText(_translate("moRFeus_Qt", "Version 0.369", None))
        self.actionOpen_SDRplot.setText(_translate("moRFeus_Qt", "Open SDRplot", None))
        self.actionVersion_0_969.setText(_translate("moRFeus_Qt", "Version 0.969", None))
        self.actionMessenger.setText(_translate("moRFeus_Qt", "Messenger", None))
